language: c
script: bash -e .travis-ci.sh
cache: apt
os:
  - linux
env:
  matrix:
    - OCAML_VERSION=4.02.0 OPAM_VERSION=1.2.0 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.02.0 OPAM_VERSION=1.2.0 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.0 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.2 OPAM_VERSION=1.2.0 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.02.2 OPAM_VERSION=1.2.0 CONFIG="--disable-ppx"
