language: c
sudo: false
cache: apt

# required APT packages
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev

script: bash -ue .travis-ci.sh

os:
  - linux
env:
  matrix:
    - OCAML_VERSION=4.00.1 OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.0 OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.2 OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.03.0+trunk OPAM_VERSION=1.2.2 CONFIG="--disable-ppx"
    - OCAML_VERSION=4.02.0 OPAM_VERSION=1.2.2 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.02.1 OPAM_VERSION=1.2.2 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.02.2 OPAM_VERSION=1.2.2 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.02.3 OPAM_VERSION=1.2.2 CONFIG="--enable-ppx"
    - OCAML_VERSION=4.03.0+trunk OPAM_VERSION=1.2.2 CONFIG="--enable-ppx"
